_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>Kehre zurück in den Spielbereich</t><br/>", "PLAIN", -1, true, true];};
sleep 2;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>10 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>9 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>8 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>7 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>6 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>5 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>4 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>3 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>2 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {titleText ["<t color='#ff0000' size='5'>1 Sekunden</t><br/>", "PLAIN", -1, true, true];};
sleep 1;
_inArea = player inArea trigger1;
_inArea2 = player inArea trigger2;
_inArea3 = player inArea trigger3;
if (_inArea || _inArea2 || _inArea3) then {execVM "restriction\deletion.sqf"} else {player setDamage 1};