[East, "techEast"] call BIS_fnc_addRespawnInventory;
[West, "techWest"] call BIS_fnc_addRespawnInventory;
[East, "medicEast"] call BIS_fnc_addRespawnInventory;
[West, "medicWest"] call BIS_fnc_addRespawnInventory;
[East, "sniperEast"] call BIS_fnc_addRespawnInventory;
[West, "sniperWest"] call BIS_fnc_addRespawnInventory;
[East, "scoutEast"] call BIS_fnc_addRespawnInventory;
[West, "scoutWest"] call BIS_fnc_addRespawnInventory;
[East, "assassinEast"] call BIS_fnc_addRespawnInventory;
[West, "assassinWest"] call BIS_fnc_addRespawnInventory;
[East, "explosiveEast"] call BIS_fnc_addRespawnInventory;
[West, "explosiveWest"] call BIS_fnc_addRespawnInventory;
nul = [[], "mechanics\gameStart.sqf"] remoteExec ["execVM", 2];