	[West, "MEDIC"] call BIS_fnc_addRespawnInventory;
	[West, "SMOKE"] call BIS_fnc_addRespawnInventory;
	[West, "AUTO"] call BIS_fnc_addRespawnInventory;
	[West, "SNIPER"] call BIS_fnc_addRespawnInventory;
	[West, "SCOUT"] call BIS_fnc_addRespawnInventory;
	[West, "ASSASSIN"] call BIS_fnc_addRespawnInventory;
	[West, "GRENADIER"] call BIS_fnc_addRespawnInventory;
	[West, "MINE"] call BIS_fnc_addRespawnInventory;
	[East, "MEDIC1"] call BIS_fnc_addRespawnInventory;
	[East, "SMOKE1"] call BIS_fnc_addRespawnInventory;
	[East, "AUTO1"] call BIS_fnc_addRespawnInventory;
	[East, "SNIPER1"] call BIS_fnc_addRespawnInventory;
	[East, "SCOUT1"] call BIS_fnc_addRespawnInventory;
	[East, "ASSASSIN1"] call BIS_fnc_addRespawnInventory;
	[East, "GRENADIER1"] call BIS_fnc_addRespawnInventory;
	[East, "MINE1"] call BIS_fnc_addRespawnInventory;
	//[] spawn compileFinal preprocessFileLineNumbers "setRandomWeather-lukas.sqf";
	//nul = execVM "watchtower\watchtower.sqf";
	//nul = execVM "mechanics\setRandomWeather-lukas.sqf";
	//TEST